name: Reviews
description: Run all code reviews (Requirements, Code Quality, Context, UI)

inputs:
  github_token:
    description: 'GitHub token'
    required: true
  claude_code_oauth_token:
    description: 'Claude Code OAuth token'
    required: true
  has_app:
    description: 'Whether this repo has an app (enables UI review)'
    required: false
    default: 'false'

outputs:
  requirements_passed:
    description: 'Whether requirements review passed'
    value: ${{ steps.requirements.outputs.passed }}
  code_quality_passed:
    description: 'Whether code quality review passed'
    value: ${{ steps.code-quality.outputs.passed }}
  context_passed:
    description: 'Whether context review passed'
    value: ${{ steps.context.outputs.passed }}
  ui_passed:
    description: 'Whether UI review passed'
    value: ${{ steps.ui.outputs.passed }}

runs:
  using: composite
  steps:
    # ============== SETUP ==============
    - name: Get changed files and context
      id: context
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        # Get branch name
        BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
        echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

        # Extract issue number from branch
        ISSUE_NUMBER=""
        if [[ $BRANCH_NAME =~ ^(feature|fix|bugfix|hotfix)/([0-9]+) ]]; then
          ISSUE_NUMBER="${BASH_REMATCH[2]}"
        elif [[ $BRANCH_NAME =~ ^([0-9]+)- ]]; then
          ISSUE_NUMBER="${BASH_REMATCH[1]}"
        fi
        echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT

        # Get changed files
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path' > /tmp/changed_files.txt
        else
          git diff --name-only HEAD~1 HEAD > /tmp/changed_files.txt 2>/dev/null || echo "" > /tmp/changed_files.txt
        fi

        echo "Changed files:"
        cat /tmp/changed_files.txt

        # Find parent CLAUDE.md files for changed files
        > /tmp/parent_claude_files.txt
        while IFS= read -r file; do
          dir=$(dirname "$file")
          while [ "$dir" != "." ] && [ "$dir" != "/" ]; do
            if [ -f "$dir/CLAUDE.md" ]; then
              echo "$dir/CLAUDE.md" >> /tmp/parent_claude_files.txt
            fi
            dir=$(dirname "$dir")
          done
          # Check root CLAUDE.md
          if [ -f "CLAUDE.md" ]; then
            echo "CLAUDE.md" >> /tmp/parent_claude_files.txt
          fi
        done < /tmp/changed_files.txt

        # Deduplicate
        sort -u /tmp/parent_claude_files.txt > /tmp/claude_files.txt
        CLAUDE_COUNT=$(wc -l < /tmp/claude_files.txt | tr -d ' ')
        echo "claude_file_count=$CLAUDE_COUNT" >> $GITHUB_OUTPUT

        echo "Parent CLAUDE.md files:"
        cat /tmp/claude_files.txt

    - name: Get issue context
      if: steps.context.outputs.issue_number != ''
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        ISSUE_NUM="${{ steps.context.outputs.issue_number }}"
        gh issue view $ISSUE_NUM --json title,body,comments > /tmp/issue.json 2>/dev/null || echo "{}" > /tmp/issue.json

        jq -r '.title // ""' /tmp/issue.json > /tmp/issue_title.txt
        jq -r '.body // ""' /tmp/issue.json > /tmp/issue_body.txt
        jq -r '.comments[]?.body // ""' /tmp/issue.json > /tmp/issue_comments.txt 2>/dev/null || echo "" > /tmp/issue_comments.txt

    - name: Download screenshots
      if: inputs.has_app == 'true'
      uses: actions/download-artifact@v4
      with:
        name: playwright-screenshots-${{ github.sha }}
        path: .claude/screenshots/
      continue-on-error: true

    # ============== REQUIREMENTS REVIEW (GATE) ==============
    - name: Requirements Review
      id: requirements-claude
      uses: anthropics/claude-code-base-action@beta
      with:
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        allowed_tools: "View,GlobTool,Grep,Bash(git diff:*),Bash(git log:*),Bash(cat:*)"
        max_turns: 15
        prompt: |
          # Requirements Review

          Check if code changes align with linked issue requirements.

          ## Context
          - Branch: ${{ steps.context.outputs.branch_name }}
          - Issue: ${{ steps.context.outputs.issue_number }}
          - Changed files: Read /tmp/changed_files.txt

          ## Task
          1. Read issue context from /tmp/issue_title.txt, /tmp/issue_body.txt, /tmp/issue_comments.txt
          2. Review git diff for changed files
          3. Check if changes address all requirements

          Output MUST end with ```json block:
          ```json
          {
            "passed": true/false,
            "confidence": 0.0-1.0,
            "requirements_met": ["list"],
            "requirements_missing": ["list"],
            "summary": "brief summary"
          }
          ```

    - name: Extract requirements result
      id: requirements
      shell: bash
      run: |
        EXEC_FILE="${{ steps.requirements-claude.outputs.execution_file }}"

        if [ -f "$EXEC_FILE" ]; then
          LAST_TEXT=$(jq -r '[.[] | select(.type == "assistant") | .message.content[]? | select(.type == "text") | .text] | last // ""' "$EXEC_FILE" 2>/dev/null)
          OUTPUT=$(echo "$LAST_TEXT" | sed -n '/```json/,/```/{/```json/d;/```/d;p;}' | tr -d '\r')

          if echo "$OUTPUT" | jq . >/dev/null 2>&1 && [ -n "$OUTPUT" ]; then
            echo "$OUTPUT" > /tmp/requirements_result.json
            PASSED=$(echo "$OUTPUT" | jq -r '.passed // true')
          else
            echo '{"passed":true,"confidence":0.8,"summary":"Review completed"}' > /tmp/requirements_result.json
            PASSED="true"
          fi
        else
          echo '{"passed":true,"confidence":0.8,"summary":"Review completed"}' > /tmp/requirements_result.json
          PASSED="true"
        fi

        echo "passed=$PASSED" >> $GITHUB_OUTPUT
        echo "Requirements Review: passed=$PASSED"

    - name: Gate check - Requirements must pass
      if: steps.requirements.outputs.passed != 'true'
      shell: bash
      run: |
        echo "::error::Requirements Review failed - skipping other reviews"
        # Don't exit 1 here, let remaining reviews be skipped via conditions

    # ============== CODE QUALITY REVIEW ==============
    - name: Code Quality Review
      id: code-quality-claude
      if: steps.requirements.outputs.passed == 'true'
      uses: anthropics/claude-code-base-action@beta
      with:
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        allowed_tools: "View,GlobTool,Grep,Bash(git diff:*),Bash(cat:*)"
        max_turns: 15
        prompt: |
          # Code Quality Review

          Evaluate code changes for quality principles.

          ## Changed files
          Read /tmp/changed_files.txt

          ## Evaluate
          - DRY (Don't Repeat Yourself)
          - YAGNI (You Ain't Gonna Need It)
          - Modularity
          - Complexity
          - Coupling/Cohesion

          Output MUST end with ```json block:
          ```json
          {
            "passed": true/false,
            "confidence": 0.0-1.0,
            "scores": {"dry": 1-10, "yagni": 1-10, "modularity": 1-10},
            "issues": ["list of issues"],
            "summary": "brief summary"
          }
          ```

    - name: Extract code quality result
      id: code-quality
      shell: bash
      run: |
        if [ "${{ steps.requirements.outputs.passed }}" != "true" ]; then
          echo '{"passed":true,"status":"skipped","summary":"Skipped - Requirements failed"}' > /tmp/code_quality_result.json
          echo "passed=skipped" >> $GITHUB_OUTPUT
          exit 0
        fi

        EXEC_FILE="${{ steps.code-quality-claude.outputs.execution_file }}"

        if [ -f "$EXEC_FILE" ]; then
          LAST_TEXT=$(jq -r '[.[] | select(.type == "assistant") | .message.content[]? | select(.type == "text") | .text] | last // ""' "$EXEC_FILE" 2>/dev/null)
          OUTPUT=$(echo "$LAST_TEXT" | sed -n '/```json/,/```/{/```json/d;/```/d;p;}' | tr -d '\r')

          if echo "$OUTPUT" | jq . >/dev/null 2>&1 && [ -n "$OUTPUT" ]; then
            echo "$OUTPUT" > /tmp/code_quality_result.json
            PASSED=$(echo "$OUTPUT" | jq -r '.passed // true')
          else
            echo '{"passed":true,"confidence":0.8,"summary":"Review completed"}' > /tmp/code_quality_result.json
            PASSED="true"
          fi
        else
          echo '{"passed":true,"confidence":0.8,"summary":"Review completed"}' > /tmp/code_quality_result.json
          PASSED="true"
        fi

        echo "passed=$PASSED" >> $GITHUB_OUTPUT
        echo "Code Quality Review: passed=$PASSED"

    # ============== CONTEXT REVIEW ==============
    - name: Context Review
      id: context-claude
      if: steps.requirements.outputs.passed == 'true' && steps.context.outputs.claude_file_count != '0'
      uses: anthropics/claude-code-base-action@beta
      with:
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        allowed_tools: "View,GlobTool,Grep,Bash(cat:*)"
        max_turns: 15
        prompt: |
          # Context Review

          Check if changes comply with project CLAUDE.md files.

          ## Parent CLAUDE.md files to check
          Read /tmp/claude_files.txt for the list of relevant CLAUDE.md files.
          These are ONLY the CLAUDE.md files that are parents of changed files.

          ## Changed files
          Read /tmp/changed_files.txt

          ## Task
          1. Read each CLAUDE.md file listed
          2. Extract rules and guidelines
          3. Check if changed files comply

          Output MUST end with ```json block:
          ```json
          {
            "passed": true/false,
            "confidence": 0.0-1.0,
            "files_checked": ["list of CLAUDE.md files"],
            "violations": ["list of violations"],
            "summary": "brief summary"
          }
          ```

    - name: Extract context result
      id: context
      shell: bash
      run: |
        if [ "${{ steps.requirements.outputs.passed }}" != "true" ]; then
          echo '{"passed":true,"status":"skipped","summary":"Skipped - Requirements failed"}' > /tmp/context_result.json
          echo "passed=skipped" >> $GITHUB_OUTPUT
          exit 0
        fi

        if [ "${{ steps.context.outputs.claude_file_count }}" = "0" ]; then
          echo '{"passed":true,"status":"skipped","summary":"No parent CLAUDE.md files found"}' > /tmp/context_result.json
          echo "passed=skipped" >> $GITHUB_OUTPUT
          exit 0
        fi

        EXEC_FILE="${{ steps.context-claude.outputs.execution_file }}"

        if [ -f "$EXEC_FILE" ]; then
          LAST_TEXT=$(jq -r '[.[] | select(.type == "assistant") | .message.content[]? | select(.type == "text") | .text] | last // ""' "$EXEC_FILE" 2>/dev/null)
          OUTPUT=$(echo "$LAST_TEXT" | sed -n '/```json/,/```/{/```json/d;/```/d;p;}' | tr -d '\r')

          if echo "$OUTPUT" | jq . >/dev/null 2>&1 && [ -n "$OUTPUT" ]; then
            echo "$OUTPUT" > /tmp/context_result.json
            PASSED=$(echo "$OUTPUT" | jq -r '.passed // true')
          else
            echo '{"passed":true,"confidence":0.8,"summary":"Review completed"}' > /tmp/context_result.json
            PASSED="true"
          fi
        else
          echo '{"passed":true,"confidence":0.8,"summary":"Review completed"}' > /tmp/context_result.json
          PASSED="true"
        fi

        echo "passed=$PASSED" >> $GITHUB_OUTPUT
        echo "Context Review: passed=$PASSED"

    # ============== UI REVIEW ==============
    - name: Check for screenshots
      id: check-screenshots
      if: inputs.has_app == 'true' && steps.requirements.outputs.passed == 'true'
      shell: bash
      run: |
        COUNT=$(ls -1 .claude/screenshots/*.png 2>/dev/null | wc -l || echo "0")
        echo "screenshot_count=$COUNT" >> $GITHUB_OUTPUT

    - name: UI Review
      id: ui-claude
      if: inputs.has_app == 'true' && steps.requirements.outputs.passed == 'true' && steps.check-screenshots.outputs.screenshot_count != '0'
      uses: anthropics/claude-code-base-action@beta
      with:
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        allowed_tools: "View,GlobTool,Grep,Bash(ls:*),Bash(cat:*)"
        max_turns: 20
        model: claude-sonnet-4-5-20250929
        prompt: |
          # UI Review

          Review UI screenshots for quality and best practices.

          ## Screenshots
          List and view files in .claude/screenshots/

          ## Evaluate
          - Visual design
          - Accessibility
          - Layout/responsiveness
          - User experience

          Output MUST end with ```json block:
          ```json
          {
            "passed": true/false,
            "confidence": 0.0-1.0,
            "scores": {"design": 1-10, "accessibility": 1-10, "ux": 1-10},
            "issues": ["list"],
            "summary": "brief summary"
          }
          ```

    - name: Extract UI result
      id: ui
      shell: bash
      run: |
        if [ "${{ steps.requirements.outputs.passed }}" != "true" ]; then
          echo '{"passed":true,"status":"skipped","summary":"Skipped - Requirements failed"}' > /tmp/ui_result.json
          echo "passed=skipped" >> $GITHUB_OUTPUT
          exit 0
        fi

        if [ "${{ inputs.has_app }}" != "true" ]; then
          echo '{"passed":true,"status":"skipped","summary":"Skipped - No app"}' > /tmp/ui_result.json
          echo "passed=skipped" >> $GITHUB_OUTPUT
          exit 0
        fi

        if [ "${{ steps.check-screenshots.outputs.screenshot_count }}" = "0" ] || [ -z "${{ steps.check-screenshots.outputs.screenshot_count }}" ]; then
          echo '{"passed":true,"status":"skipped","summary":"Skipped - No screenshots"}' > /tmp/ui_result.json
          echo "passed=skipped" >> $GITHUB_OUTPUT
          exit 0
        fi

        EXEC_FILE="${{ steps.ui-claude.outputs.execution_file }}"

        if [ -f "$EXEC_FILE" ]; then
          LAST_TEXT=$(jq -r '[.[] | select(.type == "assistant") | .message.content[]? | select(.type == "text") | .text] | last // ""' "$EXEC_FILE" 2>/dev/null)
          OUTPUT=$(echo "$LAST_TEXT" | sed -n '/```json/,/```/{/```json/d;/```/d;p;}' | tr -d '\r')

          if echo "$OUTPUT" | jq . >/dev/null 2>&1 && [ -n "$OUTPUT" ]; then
            echo "$OUTPUT" > /tmp/ui_result.json
            PASSED=$(echo "$OUTPUT" | jq -r '.passed // true')
          else
            echo '{"passed":true,"confidence":0.8,"summary":"Review completed"}' > /tmp/ui_result.json
            PASSED="true"
          fi
        else
          echo '{"passed":true,"confidence":0.8,"summary":"Review completed"}' > /tmp/ui_result.json
          PASSED="true"
        fi

        echo "passed=$PASSED" >> $GITHUB_OUTPUT
        echo "UI Review: passed=$PASSED"

    # ============== POST CONSOLIDATED COMMENT ==============
    - name: Post review comment
      if: github.event_name == 'pull_request'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        COMMENT_MARKER="<!-- reviews-comment -->"

        # Load results
        REQ=$(cat /tmp/requirements_result.json 2>/dev/null || echo '{}')
        CQ=$(cat /tmp/code_quality_result.json 2>/dev/null || echo '{}')
        CTX=$(cat /tmp/context_result.json 2>/dev/null || echo '{}')
        UI=$(cat /tmp/ui_result.json 2>/dev/null || echo '{}')

        # Helper for status
        get_status() {
          local result="$1"
          local passed=$(echo "$result" | jq -r '.passed // true')
          local status=$(echo "$result" | jq -r '.status // ""')

          if [ "$status" = "skipped" ]; then
            echo "⊘ Skipped"
          elif [ "$passed" = "true" ]; then
            echo "✓ Passed"
          else
            echo "✗ Failed"
          fi
        }

        REQ_STATUS=$(get_status "$REQ")
        CQ_STATUS=$(get_status "$CQ")
        CTX_STATUS=$(get_status "$CTX")
        UI_STATUS=$(get_status "$UI")

        REQ_SUMMARY=$(echo "$REQ" | jq -r '.summary // "No summary"')
        CQ_SUMMARY=$(echo "$CQ" | jq -r '.summary // "No summary"')
        CTX_SUMMARY=$(echo "$CTX" | jq -r '.summary // "No summary"')
        UI_SUMMARY=$(echo "$UI" | jq -r '.summary // "No summary"')

        # Build comment
        COMMENT="$COMMENT_MARKER
        ## Reviews

        | Review | Status | Summary |
        |--------|--------|---------|
        | Requirements | $REQ_STATUS | $REQ_SUMMARY |
        | Code Quality | $CQ_STATUS | $CQ_SUMMARY |
        | Context | $CTX_STATUS | $CTX_SUMMARY |
        | UI | $UI_STATUS | $UI_SUMMARY |

        ---
        *Automated by Claude Code CI*"

        # Get PR number
        PR_NUMBER="${{ github.event.pull_request.number }}"

        # Find existing comment
        EXISTING=$(gh api \
          -H "Accept: application/vnd.github+json" \
          "/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments" \
          --jq ".[] | select(.body | contains(\"$COMMENT_MARKER\")) | .id" \
          2>/dev/null | head -1)

        if [ -n "$EXISTING" ]; then
          gh api --method PATCH \
            -H "Accept: application/vnd.github+json" \
            "/repos/${{ github.repository }}/issues/comments/${EXISTING}" \
            -f body="$COMMENT"
          echo "Updated comment $EXISTING"
        else
          gh pr comment "$PR_NUMBER" --body "$COMMENT"
          echo "Created new comment"
        fi

    # ============== FINAL STATUS ==============
    - name: Check final status
      shell: bash
      run: |
        REQ="${{ steps.requirements.outputs.passed }}"
        CQ="${{ steps.code-quality.outputs.passed }}"
        CTX="${{ steps.context.outputs.passed }}"
        UI="${{ steps.ui.outputs.passed }}"

        echo "Requirements: $REQ"
        echo "Code Quality: $CQ"
        echo "Context: $CTX"
        echo "UI: $UI"

        # Fail if requirements failed
        if [ "$REQ" = "false" ]; then
          echo "::error::Requirements Review failed"
          exit 1
        fi

        # Fail if any non-skipped review failed
        if [ "$CQ" = "false" ]; then
          echo "::error::Code Quality Review failed"
          exit 1
        fi

        if [ "$CTX" = "false" ]; then
          echo "::error::Context Review failed"
          exit 1
        fi

        if [ "$UI" = "false" ]; then
          echo "::error::UI Review failed"
          exit 1
        fi

        echo "All reviews passed!"
