name: UI Review
description: Reviews UI screenshots from Playwright tests against best practices

inputs:
  github_token:
    description: 'GitHub token for API access'
    required: true
  claude_code_oauth_token:
    description: 'Claude Code OAuth token'
    required: true

outputs:
  passed:
    description: 'Whether the review passed'
    value: ${{ steps.result.outputs.passed }}
  result_json:
    description: 'Full JSON result'
    value: ${{ steps.result.outputs.result_json }}

runs:
  using: composite
  steps:
    - name: Check if UI files changed
      id: filter
      uses: dorny/paths-filter@v3
      with:
        filters: |
          ui:
            - 'apps/**'
            - 'packages/ui/**'
            - '**/*.tsx'
            - '**/*.css'
            - '**/tailwind.config.*'

    - name: Download screenshots
      if: steps.filter.outputs.ui == 'true'
      uses: actions/download-artifact@v4
      with:
        name: playwright-screenshots-${{ github.sha }}
        path: .claude/screenshots/
      continue-on-error: true

    - name: Extract context
      if: steps.filter.outputs.ui == 'true'
      id: context
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
        echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

        # Get changed UI files
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          CHANGED_FILES=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path' | grep -E '\.(tsx|css|scss)$' || echo "")
        else
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD | grep -E '\.(tsx|css|scss)$' || echo "")
        fi
        echo "$CHANGED_FILES" > /tmp/changed_ui_files.txt

        # Check for screenshots
        SCREENSHOT_COUNT=$(ls -1 .claude/screenshots/*.png 2>/dev/null | wc -l || echo "0")
        echo "screenshot_count=$SCREENSHOT_COUNT" >> $GITHUB_OUTPUT

    - name: Gather UI rules
      if: steps.filter.outputs.ui == 'true'
      id: rules
      shell: bash
      run: |
        mkdir -p /tmp/ui-rules

        # Look for ui-prefixed skills
        find .claude/skills -name "ui-*" -type d 2>/dev/null | while read -r dir; do
          if [ -f "$dir/SKILL.md" ]; then
            cp "$dir/SKILL.md" "/tmp/ui-rules/$(basename $dir).md"
          fi
        done

        # Look for UI rules in .claude/rules
        find .claude/rules -name "ui-*" -o -name "*-ui-*" 2>/dev/null | while read -r file; do
          cp "$file" "/tmp/ui-rules/" 2>/dev/null || true
        done

        RULES_COUNT=$(ls -1 /tmp/ui-rules/*.md 2>/dev/null | wc -l || echo "0")
        echo "rules_count=$RULES_COUNT" >> $GITHUB_OUTPUT

    - name: Run UI Review
      if: steps.filter.outputs.ui == 'true'
      id: review
      uses: anthropics/claude-code-base-action@beta
      with:
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        allowed_tools: "View,GlobTool,Grep,Bash(cat:*),Bash(find:*),Bash(ls:*)"
        max_turns: 25
        model: claude-sonnet-4-5-20250929
        prompt: |
          # UI Review Agent

          You are a UI review specialist. Your job is to review UI screenshots from Playwright tests and evaluate them against UI rules and modern best practices.

          ## Context
          - Branch: ${{ steps.context.outputs.branch_name }}
          - Screenshot Count: ${{ steps.context.outputs.screenshot_count }}
          - UI Rules Count: ${{ steps.rules.outputs.rules_count }}

          ## Your Task

          1. **Review screenshots** (in .claude/screenshots/):
             - List files in .claude/screenshots/ directory
             - View each screenshot file
             - Note the file path for context on what UI element it shows

          2. **Check against UI rules** (in /tmp/ui-rules/):
             - Read each UI rule/skill file
             - Evaluate screenshots against documented standards

          3. **Evaluate against modern UI best practices**:

             **Visual Design:**
             - Clear visual hierarchy
             - Consistent spacing (8px grid)
             - Accessible color contrast (WCAG 2.1 AA: 4.5:1 minimum)
             - Readable typography
             - Dark/light mode support if applicable

             **Layout & Responsiveness:**
             - Mobile-first approach
             - Proper responsive breakpoints
             - No layout shifts or overflow issues

             **Accessibility:**
             - Visible focus indicators
             - Proper touch targets (44x44px minimum)
             - Semantic structure visible in UI

             **User Experience:**
             - Clear call-to-action buttons
             - Logical flow and navigation
             - Loading and error states handled
             - Empty states designed

             **Modern Elegance:**
             - Clean, uncluttered design
             - Consistent component styling
             - Appropriate use of whitespace
             - Professional and polished appearance

          4. **Categorize issues**:
             - **Critical**: Broken layout, missing content, accessibility violations
             - **Major**: Poor UX, inconsistent styling, confusing navigation
             - **Minor**: Small visual tweaks, optimization opportunities

          5. **Make your decision**:
             - PASS: No critical issues, acceptable visual quality
             - FAIL: Critical issues found

          ## IMPORTANT RULES

          - **DO NOT edit any files** - you are a reviewer only
          - If no screenshots available, note this and PASS with a note
          - Be specific about which screenshot shows each issue
          - Suggest concrete improvements

          ## Output Format

          Your response MUST end with a JSON code block in this exact format:

          ```json
          {
            "passed": true/false,
            "confidence": 0.0-1.0,
            "screenshot_reviews": [
              {
                "screenshot_path": "path/to/screenshot.png",
                "description": "what this screenshot shows",
                "critical_issues": ["critical issues"],
                "major_issues": ["major issues"],
                "minor_issues": ["minor issues"],
                "positive_aspects": ["good things"]
              }
            ],
            "best_practices_evaluation": {
              "visual_design": 1-10,
              "layout_responsiveness": 1-10,
              "accessibility": 1-10,
              "user_experience": 1-10,
              "modern_elegance": 1-10
            },
            "total_critical": 0,
            "total_major": 0,
            "total_minor": 0,
            "top_recommendations": ["recommendations"],
            "summary": "Brief summary of your decision"
          }
          ```

    - name: Extract result
      id: result
      shell: bash
      run: |
        # Check if UI review was skipped
        if [ "${{ steps.filter.outputs.ui }}" != "true" ]; then
          echo '{"passed":true,"status":"skipped","summary":"No UI files changed"}' > /tmp/review_output.json
          echo "passed=true" >> $GITHUB_OUTPUT
          echo "result_json=$(cat /tmp/review_output.json | jq -c '.')" >> $GITHUB_OUTPUT
          exit 0
        fi

        EXEC_FILE="${{ steps.review.outputs.execution_file }}"
        CONCLUSION="${{ steps.review.outputs.conclusion }}"

        if [ "$CONCLUSION" = "success" ]; then
          DEFAULT_OUTPUT='{"passed":true,"confidence":0.8,"summary":"Review completed successfully","status":"passed"}'
        else
          DEFAULT_OUTPUT='{"passed":false,"confidence":0.5,"summary":"Review completed with issues","status":"failed"}'
        fi

        if [ -f "$EXEC_FILE" ]; then
          LAST_TEXT=$(jq -r '[.[] | select(.type == "assistant") | .message.content[]? | select(.type == "text") | .text] | last // ""' "$EXEC_FILE" 2>/dev/null)
          OUTPUT=$(echo "$LAST_TEXT" | sed -n '/```json/,/```/{/```json/d;/```/d;p;}' | tr -d '\r')

          if echo "$OUTPUT" | jq . >/dev/null 2>&1 && [ -n "$OUTPUT" ]; then
            PASSED=$(echo "$OUTPUT" | jq -r '.passed // false')
            if [ "$PASSED" = "true" ]; then
              OUTPUT=$(echo "$OUTPUT" | jq '. + {status: "passed"}')
            else
              OUTPUT=$(echo "$OUTPUT" | jq '. + {status: "failed"}')
            fi
            echo "$OUTPUT" > /tmp/review_output.json
          else
            echo "$DEFAULT_OUTPUT" > /tmp/review_output.json
          fi
        else
          echo "$DEFAULT_OUTPUT" > /tmp/review_output.json
        fi

        PASSED=$(jq -r '.passed // false' /tmp/review_output.json)
        echo "passed=$PASSED" >> $GITHUB_OUTPUT

        RESULT_JSON=$(cat /tmp/review_output.json | jq -c '.')
        echo "result_json=$RESULT_JSON" >> $GITHUB_OUTPUT
